export const people = [
    {
        "fname": "William",
        "lname": "Coffey",
        "department": "IT",
        "telephone": "2463890400",
        "email": "wcoffeey@fake.com",
    },{
        "fname": "Betty",
        "lname": "Farmer",
        "department": "Clerk",
        "telephone": "2463890401",
        "email": "bfarmer@fake.com",
    },{
        "fname": "Angela",
        "lname": "Acker",
        "department": "Treasury",
        "telephone": "2463890402",
        "email": "aacker@fake.com",
    },{
        "fname": "Jeffrey",
        "lname": "Johnson",
        "department": "Police",
        "telephone": "2463890403",
        "email": "jjohnson@fake.com",
    },{
        "fname": "Megan",
        "lname": "Hennessy",
        "department": "Fire",
        "telephone": "2463890404",
        "email": "mhennessy@fake.com",
    },{
        "fname": "Amanda",
        "lname": "Daniel",
        "department": "IT",
        "telephone": "2463890405",
        "email": "adaniel@fake.com",
    },{
        "fname": "Gloria",
        "lname": "Rasmussen",
        "department": "HR",
        "telephone": "2463890406",
        "email": "grasmussen@fake.com",
    },{
        "fname": "Terrance",
        "lname": "Lopez",
        "department": "Police",
        "telephone": "2463890407",
        "email": "tlopez@fake.com",
    },{
        "fname": "Joyce",
        "lname": "Bone",
        "department": "Clerk",
        "telephone": "2463890408",
        "email": "jbone@fake.com",
    },{
        "fname": "Vance",
        "lname": "Parks",
        "department": "IT",
        "telephone": "2463890409",
        "email": "vparks@fake.com",
    },{
        "fname": "Elizabeth",
        "lname": "McCaffrey",
        "department": "Clerk",
        "telephone": "2463890410",
        "email": "emccaffrey@fake.com",
    },{
        "fname": "Jeremiah",
        "lname": "Sims",
        "department": "IT",
        "telephone": "2463890411",
        "email": "jsims@fake.com",
    },{
        "fname": "Thomas",
        "lname": "Bucket",
        "department": "Police",
        "telephone": "2463890412",
        "email": "tbucket@fake.com",
    },{
        "fname": "Caidy",
        "lname": "Tsar",
        "department": "IT",
        "telephone": "2463890413",
        "email": "ctsar@fake.com",
    },
]